version: "3"
services:
  db:
    image: mysql:latest
    volumes: 
      - "./data::/var/lib/mysql"
    env: MYSQL_ROOT_PASSWORD:123456
  backend:
    dockerfile: ./todolist-backend
    link: db
    ports: 
      - "8080:8080"
#  frontend:
#    dockerfile: ./todolist-frontend
