version: "3"
services:
  db:
    image: "mysql:latest"
    volumes: 
      - "./data:/var/lib/mysql"
    environment: 
      - MYSQL_ROOT_PASSWORD:123456
  backend:
    build: "./todolist-backend/"
    links: 
      - "db"
    ports: 
      - "8080:8080"
  frontend:
    build: "./todolist-frontend/"
    ports: 
      - "3000:3000"
